---
apiVersion: v1
kind: Service
metadata:
  name: coredns-svc-tcp
  namespace: kube-system
spec:
  ports:
    - protocol: TCP
      port: 53
      targetPort: 53
  selector:
    k8s-app: kube-dns
  type: LoadBalancer
  loadBalancerIP: 172.17.255.10