apiVersion: v1
kind: Pod
metadata:
  name: nginx-cert-renew-example
  namespace: vault
  labels:
    app: nginx
spec:
  shareProcessNamespace: true
  serviceAccountName: vault-auth
  volumes:
  - configMap:
      items:
      - key: vault-agent-config.hcl
        path: vault-agent-config.hcl
      - key: consul-template-config.hcl
        path: consul-template-config.hcl
      name: nginx-cert-renew-config
    name: config
  - configMap:
      items:
      - key: nginx_ssl.conf
        path: nginx_ssl.conf
      name: nginx-cert-renew-config
    name: nginx-config
  - emptyDir: {}
    name: shared-data
  - emptyDir: {}
    name: vault-token    

  initContainers:
  - args:
    - agent
    - -config=/etc/vault/vault-agent-config.hcl
    - -log-level=debug
    env:
    - name: VAULT_ADDR
      value: http://vault:8200
    image: vault
    imagePullPolicy: IfNotPresent
    name: vault-agent
    volumeMounts:
    - mountPath: /etc/vault
      name: config
    - name: vault-token
      mountPath: /home/vault

  containers:
  - image: nginx
    imagePullPolicy: IfNotPresent
    name: nginx-container
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/ssl/
      name: shared-data
    - mountPath: /etc/nginx/conf.d/
      name: nginx-config
  - name: consul-template
    image: hashicorp/consul-template:alpine
    imagePullPolicy: IfNotPresent
    securityContext:
      runAsUser: 0
      capabilities:
        add:
        - SYS_PTRACE
    volumeMounts:
      - name: vault-token
        mountPath: /home/vault
      - name: config
        mountPath: /etc/consul-template
      - name: shared-data
        mountPath: /etc/secrets
    env:
      - name: HOME
        value: /home/vault
      - name: VAULT_ADDR
        value: http://vault:8200
    args: ["-config=/etc/consul-template/consul-template-config.hcl"]