#
# Helm Chart Repositories
#
repositories:
  # Stable repo of official helm charts
  - name: "stable"
    url: "https://kubernetes-charts.storage.googleapis.com"
  - name: "jetstack"
    url: "https://charts.jetstack.io"
  - name: "harbor"
    url: "https://helm.goharbor.io"
#
# Kubernetes
#
context: 'eternal-kub'

#
# Helm Releases
#
releases:
  # nginx-ingress
  - name: "http-https"
    labels:
      chart: "stable/nginx-ingress"
    chart: "stable/nginx-ingress"
    version: "1.40.2"
    namespace: "ingress"
    set:
      - name: "controller.service.type"
        value: "LoadBalancer"
      - name: "controller.service.externalTrafficPolicy"
        value: "Local"
  - name: "cert-manager"
    labels:
      chart: "jetstack/cert-manager"
    chart: "jetstack/cert-manager"
    version: "v0.15.2"
    namespace: "cert-manager"
  - name: "harbor"
    chart: "harbor/harbor"
    labels:
      chart: "harbor/harbor"
    version: "1.4.1"
    namespace: "harbor"
    values:
      - ../harbor/values.yaml
