apiVersion: v1
kind: Service
metadata:
  name: nginx-exporter
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - name: exporter
    port: 3333
    protocol: TCP
    targetPort: 3333
  selector:
    app: nginx