apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitoring
  labels:
    purpose: education
spec:
  selector:
    matchLabels:
      app: nginx
  endpoints:
  - port: "3333"