loki:
  ingress:
    enabled: true
    hosts:
    - host: loki.35.196.14.250.xip.io
      paths:
      - /

promtail:
  tolerations:
    - key: node-role
      operator: Equal
      value: infra
      effect: NoSchedule